### ISSUE TITLE
gspread.exceptions.SpreadsheetNotFound

### ISSUE THREAD

**Issue by joshuar500** [j-c-peters/spending-tracker#2]
Hello! I followed the steps exactly, my `credentials.json` is on Heroku, but for some reason I'm getting this error:

```
2019-05-05T23:28:12.835309+00:00 app[web.1]: [2019-05-05 23:28:12,832] ERROR in app: Exception on /budget/api/email [POST]
2019-05-05T23:28:12.835313+00:00 app[web.1]: Traceback (most recent call last):
2019-05-05T23:28:12.835314+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gspread/client.py", line 122, in open
2019-05-05T23:28:12.835316+00:00 app[web.1]: self.list_spreadsheet_files()
2019-05-05T23:28:12.835317+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gspread/utils.py", line 29, in finditem
2019-05-05T23:28:12.835319+00:00 app[web.1]: return next((item for item in seq if func(item)))
2019-05-05T23:28:12.835320+00:00 app[web.1]: StopIteration
2019-05-05T23:28:12.835321+00:00 app[web.1]:
2019-05-05T23:28:12.835323+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2019-05-05T23:28:12.835324+00:00 app[web.1]:
2019-05-05T23:28:12.835325+00:00 app[web.1]: Traceback (most recent call last):
2019-05-05T23:28:12.835326+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
2019-05-05T23:28:12.835327+00:00 app[web.1]: response = self.full_dispatch_request()
2019-05-05T23:28:12.835329+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
2019-05-05T23:28:12.835330+00:00 app[web.1]: rv = self.handle_user_exception(e)
2019-05-05T23:28:12.835332+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
2019-05-05T23:28:12.835333+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2019-05-05T23:28:12.835334+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
2019-05-05T23:28:12.835335+00:00 app[web.1]: raise value
2019-05-05T23:28:12.835336+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
2019-05-05T23:28:12.835337+00:00 app[web.1]: rv = self.dispatch_request()
2019-05-05T23:28:12.835339+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
2019-05-05T23:28:12.835340+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2019-05-05T23:28:12.835341+00:00 app[web.1]: File "/app/app.py", line 45, in parse_email
2019-05-05T23:28:12.835342+00:00 app[web.1]: sheet.add_expense(amount, description, category, method)
2019-05-05T23:28:12.835343+00:00 app[web.1]: File "/app/sheets.py", line 14, in add_expense
2019-05-05T23:28:12.835344+00:00 app[web.1]: sheet = self.client.open('Budget').sheet1
2019-05-05T23:28:12.835345+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gspread/client.py", line 130, in open
2019-05-05T23:28:12.835347+00:00 app[web.1]: raise SpreadsheetNotFound
2019-05-05T23:28:12.835352+00:00 app[web.1]: gspread.exceptions.SpreadsheetNotFound
2019-05-05T23:28:12.836436+00:00 app[web.1]: 10.165.209.116 - - [05/May/2019:23:28:12 +0000] "POST /budget/api/email HTTP/1.1" 500 291 "-" "Zapier"
2019-05-05T23:28:12.837251+00:00 heroku[router]: at=info method=POST path="/budget/api/email" host=budgeting-app-api-heroku.herokuapp.com request_id=2eacbfc5-d55d-4444-80f1-d74ad631d715 fwd="34.201.37.70" dyno=web.1 connect=1ms service=185ms status=500 bytes=456 protocol=https
```

**Comment by peters-josh** [comment]
When you copied the spreadsheet to your drive, did you rename it `Budget`?

**Comment by joshuar500** [comment]
I needed to share that spreadsheet with the email that was created when I set the permissions. I also ended up using `open_by_key()` to be more specific. Thanks for writing this all up though!
